### ISSUE TITLE
cipher problem

### ISSUE THREAD

**Issue by Muskan1699** [beingmartinbmc/HackerEarth-Solutions#1]
#include<stdio.h>
#include<string.h>
#include<ctype.h>
int main()
{
    int k;
    char y;
    int x;
    char a[1000];
    gets(a);
    scanf("%d",k);
    int len=strlen(a);
    int i;
    for(i=0;i<len;i++)
    {
        if(isalnum(a[i]))
        {
            if(isalpha(a[i]))
            {
                if(isupper(a[i]))
                {
                    y='A';
                }
                else
                {
                    y='a';
                }
                int x=a[i]; 
                x=y+((x+k-y)%26);
                char c=x;
                a[i]=c;
            }
            if(isdigit(a[i]))
            {
                y='0';
                int x=a[i]; 
                x=y+((x+k-y)%10);
                char c=x;
                a[i]=c;
            }
        }
    }
    printf("%s",a);
    return 0;
}
    

Hey,
This is my code for cipher problem. It is quite same but my code is showing runtime error(SIGSEGV) on hackerearth, but on running your code it worked completely well. Can you please check and tell me know where is the problem with my code.

**Comment by beingmartinbmc** [comment]
Hey sorry for the late reply. You need to have scanf("%d", &k).
Goodluck:)
